# Generated by Django 4.0.4 on 2022-05-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_studentgrades_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentactivities',
            table='student_activities',
        ),
        migrations.AlterModelTable(
            name='studentdetails',
            table='student_details',
        ),
        migrations.AlterModelTable(
            name='studentgrades',
            table='student_grades',
        ),
    ]
