# Generated by Django 4.0.4 on 2022-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_alter_studentactivities_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='contact',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
