# Generated by Django 4.0.4 on 2022-05-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_alter_studentdetails_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrades',
            old_name='total_grade',
            new_name='grade',
        ),
    ]
