# Generated by Django 4.0.4 on 2022-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_rename_total_grade_studentgrades_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentactivities',
            unique_together={('student', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgrades',
            unique_together={('physics', 'semester'), ('maths', 'semester'), ('chemistry', 'semester')},
        ),
    ]
