# Generated by Django 4.0.4 on 2022-05-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_alter_studentactivities_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgrades',
            unique_together={('student', 'maths', 'semester'), ('student', 'physics', 'semester'), ('student', 'chemistry', 'semester')},
        ),
    ]
